-- All requests up to Supabase will include a JWT, which will contain the sub claim -- which is the id of the requesting user. The following function grabs that sub, and turns it into function so that you can use it in your "RLS Policies".
create or replace function requesting_user_id() returns text as $$ select nullif(current_setting('request.jwt.claims', true)::json->>'sub', '')::text; $$ language sql stable;

-- Create a table to store your documents
CREATE TABLE posts (
  id bigint generated by default as identity primary key,
  user_id text not null,
  avatar_url text,
  username text,
  likes text array,
  title text,
  content text,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);